language: rust

os:
  - linux
  - osx

rust:
  - stable
  - beta

sudo: required

addons:
  apt:
    packages:
      - libgmp3-dev
env:
  global:
    - RUST_BACKTRACE=1
    - RUSTFLAGS="-C link-dead-code"
    - CARGO_MAKE_RUN_CODECOV=true
    - RUST_TEST_THREADS=1

before_script:
  - |
    export PATH=`pwd`:$PATH && if [ "$TRAVIS_OS_NAME" == "linux" ] ; then
      wget https://github.com/Z3Prover/z3/releases/download/z3-4.5.0/z3-4.5.0-x64-ubuntu-14.04.zip &&
      unzip z3-4.5.0-x64-ubuntu-14.04.zip &&
      mv z3-4.5.0-x64-ubuntu-14.04/bin/z3 .
    elif [ "$TRAVIS_OS_NAME" == "osx" ] ; then
      wget https://github.com/Z3Prover/z3/releases/download/z3-4.5.0/z3-4.5.0-x64-osx-10.11.6.zip &&
      unzip z3-4.5.0-x64-osx-10.11.6.zip &&
      mv z3-4.5.0-x64-osx-10.11.6/bin/z3 . &&
      z3 -h
    fi

script:
  - cargo install --debug cargo-make
  - cargo make ci-flow