language: rust

os:
  - linux
  # - osx

rust:
  - stable
  # - beta

sudo: false

addons:
  apt:
    packages:
      - libgmp3-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - cmake
    sources:
      - kalakris-cmake

env:
  global:
  - RUSTFLAGS="-C link-dead-code"

before_script:
  - |
      cargo install cargo-travis &&
      export PATH=$HOME/.cargo/bin:$PATH
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ] ; then
      wget https://github.com/Z3Prover/z3/releases/download/z3-4.5.0/z3-4.5.0-x64-ubuntu-14.04.zip &&
      unzip z3-4.5.0-x64-ubuntu-14.04.zip &&
      mv z3-4.5.0-x64-ubuntu-14.04/bin/z3 $HOME/.local/bin/.
    elif [ "$TRAVIS_OS_NAME" == "osx" ] ; then
      wget https://github.com/Z3Prover/z3/releases/download/z3-4.5.0/z3-4.5.0-x64-osx-10.11.6.zip &&
      unzip z3-4.5.0-x64-osx-10.11.6.zip &&
      mv z3-4.5.0-x64-osx-10.11.6/bin/z3 $HOME/.local/bin/. &&
      z3 -h
    fi

script:
  - cargo build
  - cargo build --release
  - cargo test
  - cargo doc

after_success: |
  - cargo coveralls