language: rust

os:
  - linux
  - osx

rust:
  - stable
  - beta

sudo: false

cache: cargo

addons:
  apt:
    packages:
      - libgmp3-dev

before_script:
- |
  pip install 'travis-cargo<0.2' --user &&
  export PATH=$HOME/.local/bin:$PATH
- |
  if [ "$TRAVIS_OS_NAME" == "linux" ] ; then
    wget https://github.com/Z3Prover/z3/releases/download/z3-4.5.0/z3-4.5.0-x64-ubuntu-14.04.zip &&
    unzip z3-4.5.0-x64-ubuntu-14.04.zip &&
    mv z3-4.5.0-x64-ubuntu-14.04/bin/z3 $HOME/.local/bin/. &&
    z3 -h
  fi
- |
  if [ "$TRAVIS_OS_NAME" == "osx" ] ; then
    brew update &&
    brew install gmp &&
    wget https://github.com/Z3Prover/z3/releases/download/z3-4.5.0/z3-4.5.0-x64-osx-10.11.6.zip &&
    unzip z3-4.5.0-x64-osx-10.11.6.zip &&
    mv z3-4.5.0-x64-osx-10.11.6/bin/z3 $HOME/.local/bin/. &&
    z3 -h
  fi

script:
  - travis-cargo build
  - travis-cargo test
