language: rust
rust:
  - stable
  - beta

sudo: false

cache: cargo

before_script:
- |
  pip install 'travis-cargo<0.2' --user &&
  export PATH=$HOME/.local/bin:$PATH
- |
  echo "$TRAVIS_OS_NAME"
- |
  if [ "$TRAVIS_OS_NAME" == "linux" ] ; then
    wget https://github.com/Z3Prover/z3/releases/download/z3-4.5.0/z3-4.5.0-x64-debian-8.5.zip &&
    unzip z3-4.5.0-x64-debian-8.5.zip &&
    mv z3-4.5.0-x64-debian-8.5/bin/z3 $HOME/.local/bin/. &&
    z3 -h
  fi

script:
  - travis-cargo build
  - travis-cargo test

os:
  - linux