[package]
name = "rsmt2"
version = "0.4.0"
authors = ["Adrien Champion <adrien.champion@email.com>"]
description = "Wrapper for SMT Lib 2 compliant SMT solvers."
documentation = "https://docs.rs/rsmt2/0.2.0/rsmt2"
homepage = "https://github.com/kino-mc/rsmt2"
repository = "https://github.com/kino-mc/rsmt2"
readme = "README.md"
keywords = ["SMT", "SAT", "satisfiability", "solver"]
license = "MIT/Apache-2.0"

[dependencies]
error-chain = "^0"
nom = "^2"