[package]
name = "rsmt2"
version = "0.1.0"
authors = ["Adrien Champion <adrien.champion@email.com>"]
description = "Wrapper for SMT Lib 2 compliant SMT solvers."
documentation = "http://adrienchampion.bitbucket.org/rsmt2/rsmt2/"
homepage = "https://bitbucket.org/AdrienChampion/rsmt2/"
repository = "https://bitbucket.org/AdrienChampion/rsmt2/src"
readme = "README.md"
keywords = ["SMT", "SAT", "satisfiability", "wrapper", "solver"]
license = "MIT/Apache-2.0"

[[bin]]
name = "rsmt2_bin"
doc = false

[dependencies]
regex = "0.1.41"
nom = "~0.5.0"