[package]
name = "rsmt2"
version = "0.1.0"
authors = ["Adrien Champion <adrien.champion@email.com>"]

[lib]
name = "rsmt2_lib"

[dependencies.parse_comb]
git = "https://bitbucket.org/AdrienChampion/parse_comb.git"